/* ====================================================================
   DAKKU — Dativ & Akkusativ verstehen (Zusatzlektion)
   Geteilte Daten für Solo- und Firebase-Version.
   Drei Module:
     1) Die Beine-Methode (1/2/3 Beine = Nom/Akk/Dativ)
     2) Verben mit festen Präpositionen
     3) Reflexivpronomen im Akkusativ und Dativ
   ==================================================================== */

const LESSON = {
  title: "Dativ & Akkusativ verstehen",
  subtitle: "Die Beine-Methode · feste Präpositionen · Reflexivpronomen",

  modules: [
    /* ============== MODUL 1 — BEINE-METHODE ============== */
    {
      id: "beine",
      title: "Die Beine-Methode",
      icon: "🦵",
      intro: [
        { h:"Die Idee in einem Bild",
          p:"Stell dir vor, jedes Verb ist ein Tisch. Ein Tisch braucht Beine, damit er stehen kann. Manche Verben brauchen <b>ein Bein</b>, manche <b>zwei</b>, manche <b>drei</b>. Die Beine sind die Ergänzungen — und sie zeigen dir, warum es Akkusativ und Dativ gibt." },
        { h:"① Ein Bein — nur Nominativ",
          p:"Diese Verben brauchen nur eine Person/Sache, die etwas tut. Kein Objekt nötig. <br><b>schlafen, kommen, lachen, arbeiten</b><br>👉 <i>Das Kind schläft.</i> · <i>Ich komme.</i>",
          tag:"1 Bein = Subjekt (Nominativ)" },
        { h:"② Zwei Beine — Nominativ + Akkusativ",
          p:"Hier tut jemand etwas mit einer Sache. Das zweite Bein ist das <b>Akkusativ-Objekt</b> (das Ziel der Handlung).<br><b>haben, sehen, kaufen, essen, brauchen</b><br>👉 <i>Ich habe <u>einen Hund</u>.</i> · <i>Sie kauft <u>ein Brot</u>.</i>",
          tag:"2 Beine = wer? + wen/was? (Akkusativ)" },
        { h:"③ Drei Beine — Nominativ + Dativ + Akkusativ",
          p:"Diese Verben geben etwas weiter — von einer Person zu einer anderen. Das dritte Bein ist der <b>Dativ</b> (die empfangende Person).<br><b>geben, schenken, zeigen, schicken, erklären</b><br>👉 <i>Ich gebe <u>dem Kind</u> (Dativ) <u>einen Apfel</u> (Akkusativ).</i>",
          tag:"3 Beine = wer? + wem? (Dativ) + was? (Akkusativ)" },
        { h:"⚠️ Die Ausnahmen (auswendig lernen)",
          p:"Ein paar wichtige Verben haben nur <b>zwei Beine, aber das zweite ist Dativ statt Akkusativ</b>. Das ist nicht logisch — das muss man lernen:<br><b>helfen, danken, gefallen, gehören, vertrauen, antworten, folgen</b><br>👉 <i>Ich helfe <u>dem Mann</u>.</i> (nicht „den Mann“)<br>👉 <i>Das Buch gefällt <u>mir</u>.</i>",
          tag:"Dativ-Ausnahmen mit nur 2 Beinen", warn:true },
      ],
      tasks: [
        { type:"mc", qt:"Wie viele Beine?", prompt:"„schlafen“ — wie viele Beine braucht dieses Verb?",
          options:["1 Bein (nur Nominativ)","2 Beine (Nom + Akk)","3 Beine (Nom + Dat + Akk)"], correct:0,
          exp:"schlafen braucht kein Objekt: „Das Kind schläft.“ = 1 Bein." },
        { type:"mc", qt:"Wie viele Beine?", prompt:"„kaufen“ — wie viele Beine?",
          options:["2 Beine (Nom + Akk)","1 Bein","3 Beine"], correct:0,
          exp:"kaufen: wer kauft was? „Ich kaufe ein Brot.“ = 2 Beine (Akkusativ)." },
        { type:"mc", qt:"Wie viele Beine?", prompt:"„geben“ — wie viele Beine?",
          options:["3 Beine (Nom + Dat + Akk)","2 Beine","1 Bein"], correct:0,
          exp:"geben: wer gibt wem was? = 3 Beine (Dativ + Akkusativ)." },
        { type:"mc", qt:"Wie viele Beine?", prompt:"„lachen“ — wie viele Beine?",
          options:["1 Bein","2 Beine","3 Beine"], correct:0,
          exp:"lachen braucht kein Objekt: „Sie lacht.“ = 1 Bein." },
        { type:"mc", qt:"Wie viele Beine?", prompt:"„schenken“ — wie viele Beine?",
          options:["3 Beine (Nom + Dat + Akk)","2 Beine","1 Bein"], correct:0,
          exp:"schenken: wer schenkt wem was? = 3 Beine." },
        { type:"mc", qt:"Akkusativ oder Dativ?", prompt:"Ich sehe ____ Film.",
          options:["den","dem","der","des"], correct:0,
          exp:"sehen = 2 Beine, das Objekt ist Akkusativ: „den Film“." },
        { type:"mc", qt:"Akkusativ oder Dativ?", prompt:"Ich helfe ____ Mann.",
          options:["dem","den","der","das"], correct:0,
          exp:"helfen ist eine Ausnahme: Dativ! „dem Mann“." },
        { type:"mc", qt:"Akkusativ oder Dativ?", prompt:"Das Buch gefällt ____.",
          options:["mir","mich","ich","meiner"], correct:0,
          exp:"gefallen ist eine Dativ-Ausnahme: „gefällt mir“." },
        { type:"mc", qt:"Akkusativ oder Dativ?", prompt:"Sie gibt ____ Kind einen Apfel.",
          options:["dem","den","das","der"], correct:0,
          exp:"geben = 3 Beine: die empfangende Person steht im Dativ: „dem Kind“." },
        { type:"mc", qt:"Welches Bein fehlt?", prompt:"„Ich gebe einen Apfel.“ — Welches Bein fehlt?",
          options:["das Dativ-Bein (wem?)","das Akkusativ-Bein","das Nominativ-Bein","kein Bein fehlt"], correct:0,
          exp:"geben braucht 3 Beine — hier fehlt der Dativ: wem gebe ich den Apfel?" },
        { type:"gap", qt:"Dativ-Ausnahme", prompt:"Ich danke ____ Lehrerin.",
          options:["der","die","den","das"], correct:0,
          exp:"danken = Dativ-Ausnahme: „der Lehrerin“ (Dativ feminin)." },
        { type:"gap", qt:"Dativ-Ausnahme", prompt:"Wir vertrauen ____ Arzt.",
          options:["dem","den","der","das"], correct:0,
          exp:"vertrauen = Dativ-Ausnahme: „dem Arzt“." },
        { type:"gap", qt:"2 Beine (Akkusativ)", prompt:"Hast du ____ Auto?",
          options:["ein","einem","einen","eines"], correct:0,
          exp:"haben = Akkusativ. „ein Auto“ (neutrum, Akkusativ = wie Nominativ)." },
        { type:"gap", qt:"3 Beine", prompt:"Er zeigt ____ Touristen den Weg.",
          options:["dem","den","der","das"], correct:0,
          exp:"zeigen = 3 Beine: Person im Dativ „dem Touristen“, Sache im Akkusativ „den Weg“." },
        { type:"pair", qt:"Verb → Beine", prompt:"Ordne jedem Verb die richtige Beinzahl zu.",
          items:[ {l:"schlafen", r:"1 Bein"}, {l:"kaufen", r:"2 Beine"}, {l:"geben", r:"3 Beine"}, {l:"helfen", r:"2 Beine (Dativ!)"} ] },
        { type:"pair", qt:"Frage → Kasus", prompt:"Welche Frage gehört zu welchem Kasus?",
          items:[ {l:"wer? / was?", r:"Nominativ"}, {l:"wen? / was?", r:"Akkusativ"}, {l:"wem?", r:"Dativ"} ] },
        { type:"scramble", qt:"Satz bauen (3 Beine)", prompt:"Bau den Satz: Subjekt + Verb + Dativ + Akkusativ.",
          words:["Ich","gebe","dem","Kind","einen","Apfel","."], answer:"Ich gebe dem Kind einen Apfel ." },
        { type:"scramble", qt:"Satz bauen (2 Beine)", prompt:"Bau den Satz.",
          words:["Sie","kauft","einen","neuen","Mantel","."], answer:"Sie kauft einen neuen Mantel ." },
        { type:"scramble", qt:"Satz bauen (Dativ-Ausnahme)", prompt:"Bau den Satz.",
          words:["Der","Film","gefällt","meinem","Vater","."], answer:"Der Film gefällt meinem Vater ." },
        { type:"mc", qt:"Verstanden?", prompt:"Warum gibt es überhaupt einen Dativ?",
          options:["weil manche Verben drei Beine brauchen (geben wem was)","weil Dativ schöner klingt","weil es Plural anzeigt","es gibt keinen Grund"], correct:0,
          exp:"Genau: Wenn ein Verb etwas von A zu B weitergibt, braucht es ein drittes Bein — den Dativ für die empfangende Person." },
      ],
    },

    /* ============== MODUL 2 — FESTE PRÄPOSITIONEN ============== */
    {
      id: "praep",
      title: "Verben mit festen Präpositionen",
      icon: "🔗",
      intro: [
        { h:"Was ist das?",
          p:"Manche Verben haben eine <b>feste Präposition</b>, die immer dazugehört — wie ein fester Partner. Die Präposition bestimmt den Kasus, nicht das Verb.<br>👉 <i>Ich warte <b>auf</b> den Bus.</i> (warten auf + Akkusativ)" },
        { h:"Die Präposition entscheidet den Kasus",
          p:"Du musst zwei Dinge zusammen lernen: <b>Verb + Präposition + Kasus</b>.<br><b>auf + A:</b> warten auf, sich freuen auf, sich konzentrieren auf<br><b>für + A:</b> sich interessieren für, sich bedanken für, sorgen für<br><b>über + A:</b> sich freuen über, sprechen über, sich ärgern über<br><b>um + A:</b> sich bewerben um, sich kümmern um, bitten um",
          tag:"diese Präpositionen → Akkusativ" },
        { h:"Mit Dativ",
          p:"<b>mit + D:</b> sich beschäftigen mit, anfangen mit, rechnen mit<br><b>bei + D:</b> sich bewerben bei, helfen bei<br><b>von + D:</b> träumen von, abhängen von<br><b>zu + D:</b> gehören zu, passen zu<br><b>nach + D:</b> fragen nach, suchen nach",
          tag:"diese Präpositionen → Dativ" },
        { h:"Tipp: als Paket lernen",
          p:"Lerne nie nur „interessieren“. Lerne immer das ganze Paket: <b>sich interessieren für + A</b>. Schreib dir kleine Karten: vorne das Verb, hinten Präposition + Kasus + ein Beispielsatz." },
      ],
      tasks: [
        { type:"gap", qt:"Welche Präposition?", prompt:"Ich interessiere mich ____ Musik.",
          options:["für","auf","über","mit"], correct:0, exp:"sich interessieren für + Akkusativ." },
        { type:"gap", qt:"Welche Präposition?", prompt:"Wir warten ____ den Bus.",
          options:["auf","für","über","an"], correct:0, exp:"warten auf + Akkusativ." },
        { type:"gap", qt:"Welche Präposition?", prompt:"Sie bewirbt sich ____ eine Stelle.",
          options:["um","für","auf","bei"], correct:0, exp:"sich bewerben um + Akkusativ (die Stelle)." },
        { type:"gap", qt:"Welche Präposition?", prompt:"Er beschäftigt sich ____ alten Büchern.",
          options:["mit","für","auf","über"], correct:0, exp:"sich beschäftigen mit + Dativ." },
        { type:"gap", qt:"Welche Präposition?", prompt:"Ich freue mich ____ das Wochenende.",
          options:["auf","über","für","an"], correct:0, exp:"sich freuen auf + Akkusativ (Zukunft)." },
        { type:"gap", qt:"Welche Präposition?", prompt:"Ich freue mich ____ dein Geschenk.",
          options:["über","auf","für","an"], correct:0, exp:"sich freuen über + Akkusativ (jetzt/Vergangenheit)." },
        { type:"gap", qt:"Welche Präposition?", prompt:"Sie träumt ____ einer großen Reise.",
          options:["von","auf","über","für"], correct:0, exp:"träumen von + Dativ." },
        { type:"gap", qt:"Welche Präposition?", prompt:"Wir kümmern uns ____ die Kinder.",
          options:["um","für","auf","mit"], correct:0, exp:"sich kümmern um + Akkusativ." },
        { type:"gap", qt:"Welcher Kasus?", prompt:"Ich denke an ____ Urlaub. (der Urlaub)",
          options:["den","dem","der","des"], correct:0, exp:"denken an + Akkusativ: „den Urlaub“." },
        { type:"gap", qt:"Welcher Kasus?", prompt:"Sie arbeitet mit ____ Kollegen. (der Kollege)",
          options:["dem","den","der","des"], correct:0, exp:"arbeiten mit + Dativ: „dem Kollegen“." },
        { type:"mc", qt:"Akkusativ oder Dativ?", prompt:"Welche Präposition steht hier mit AKKUSATIV?",
          options:["für","mit","von","zu"], correct:0, exp:"für + Akkusativ. mit/von/zu + Dativ." },
        { type:"mc", qt:"Akkusativ oder Dativ?", prompt:"Welche Präposition steht hier mit DATIV?",
          options:["mit","für","um","über"], correct:0, exp:"mit + Dativ. für/um/über + Akkusativ." },
        { type:"pair", qt:"Verb → Präposition", prompt:"Verbinde Verb und feste Präposition.",
          items:[ {l:"sich interessieren", r:"für"}, {l:"warten", r:"auf"}, {l:"sich bewerben", r:"um / bei"}, {l:"träumen", r:"von"} ] },
        { type:"pair", qt:"Präposition → Kasus", prompt:"Welche Präposition braucht welchen Kasus?",
          items:[ {l:"für", r:"Akkusativ"}, {l:"über", r:"Akkusativ"}, {l:"mit", r:"Dativ"}, {l:"von", r:"Dativ"} ] },
        { type:"scramble", qt:"Satz bauen", prompt:"Bau den Satz.",
          words:["Ich","interessiere","mich","für","moderne","Kunst","."], answer:"Ich interessiere mich für moderne Kunst ." },
        { type:"scramble", qt:"Satz bauen", prompt:"Bau den Satz.",
          words:["Wir","warten","auf","den","nächsten","Zug","."], answer:"Wir warten auf den nächsten Zug ." },
        { type:"scramble", qt:"Satz bauen", prompt:"Bau den Satz.",
          words:["Sie","beschäftigt","sich","mit","der","Geschichte","."], answer:"Sie beschäftigt sich mit der Geschichte ." },
        { type:"gap", qt:"Welche Präposition?", prompt:"Vielen Dank — ich bedanke mich ____ deine Hilfe.",
          options:["für","über","auf","mit"], correct:0, exp:"sich bedanken für + Akkusativ." },
        { type:"gap", qt:"Welche Präposition?", prompt:"Das hängt ____ dem Wetter ab.",
          options:["von","auf","mit","über"], correct:0, exp:"abhängen von + Dativ." },
        { type:"mc", qt:"Paket erkennen", prompt:"Welches „Paket“ ist komplett richtig?",
          options:["sich konzentrieren auf + Akkusativ","sich konzentrieren für + Dativ","sich konzentrieren mit + Akkusativ","sich konzentrieren über + Dativ"], correct:0,
          exp:"sich konzentrieren auf + Akkusativ: „Ich konzentriere mich auf die Arbeit.“." },
      ],
    },

    /* ============== MODUL 3 — REFLEXIVPRONOMEN ============== */
    {
      id: "reflexiv",
      title: "Reflexivpronomen: Akkusativ & Dativ",
      icon: "🔄",
      intro: [
        { h:"Was ist ein Reflexivpronomen?",
          p:"Bei reflexiven Verben zeigt die Handlung zurück auf das Subjekt — man tut etwas für/mit sich selbst.<br>👉 <i>Ich wasche <b>mich</b>.</i> (ich = mich, dieselbe Person)" },
        { h:"Die Formen",
          p:"<b>Akkusativ:</b> mich · dich · sich · uns · euch · sich<br><b>Dativ:</b> mir · dir · sich · uns · euch · sich<br>Nur in der <b>ich-</b> und <b>du-Form</b> sieht man den Unterschied (mich/mir, dich/dir). Bei er/sie/es/Sie ist es immer „sich“." },
        { h:"Die wichtigste Regel",
          p:"Das Reflexivpronomen steht im <b>Dativ</b>, wenn im Satz schon ein <b>Akkusativobjekt</b> steht. Sonst steht es im Akkusativ.<br>👉 <i>Ich wasche <b>mich</b>.</i> (kein anderes Objekt → Akkusativ)<br>👉 <i>Ich wasche <b>mir</b> die Hände.</i> (die Hände = Akkusativ → Reflexivpronomen wird Dativ)",
          tag:"schon ein Akkusativ da? → Reflexivpronomen wird Dativ", warn:true },
        { h:"Wie bei der Beine-Methode",
          p:"Denk an die Beine: „Ich wasche mich“ = 2 Beine (mich = Akkusativ). „Ich wasche mir die Hände“ = 3 Beine: „die Hände“ nimmt das Akkusativ-Bein, also wird „mir“ zum Dativ-Bein. Genau dieselbe Logik!" },
      ],
      tasks: [
        { type:"gap", qt:"Akkusativ oder Dativ?", prompt:"Ich interessiere ____ für Sport.",
          options:["mich","mir","mein","ich"], correct:0, exp:"Kein anderes Akkusativobjekt → Reflexivpronomen im Akkusativ: „mich“." },
        { type:"gap", qt:"Akkusativ oder Dativ?", prompt:"Ich wasche ____ die Hände.",
          options:["mir","mich","meine","ich"], correct:0, exp:"„die Hände“ ist schon Akkusativ → Reflexivpronomen wird Dativ: „mir“." },
        { type:"gap", qt:"Akkusativ oder Dativ?", prompt:"Du wäschst ____.",
          options:["dich","dir","du","dein"], correct:0, exp:"kein Akkusativobjekt → „dich“ (Akkusativ)." },
        { type:"gap", qt:"Akkusativ oder Dativ?", prompt:"Du putzt ____ die Zähne.",
          options:["dir","dich","du","dein"], correct:0, exp:"„die Zähne“ = Akkusativ → Reflexivpronomen Dativ: „dir“." },
        { type:"gap", qt:"Akkusativ oder Dativ?", prompt:"Ich wünsche ____ ein neues Fahrrad.",
          options:["mir","mich","ich","meiner"], correct:0, exp:"„ein neues Fahrrad“ = Akkusativ → „mir“ (Dativ)." },
        { type:"gap", qt:"Welche Form?", prompt:"Er konzentriert ____ auf die Prüfung.",
          options:["sich","ihm","ihn","er"], correct:0, exp:"3. Person immer „sich“." },
        { type:"gap", qt:"Welche Form?", prompt:"Wir treffen ____ am Bahnhof.",
          options:["uns","unser","wir","euch"], correct:0, exp:"wir-Form: „uns“." },
        { type:"gap", qt:"Welche Form?", prompt:"Habt ihr ____ schon vorgestellt?",
          options:["euch","ihr","sich","uns"], correct:0, exp:"ihr-Form: „euch“." },
        { type:"gap", qt:"Akkusativ oder Dativ?", prompt:"Ich merke ____ die Vokabeln.",
          options:["mir","mich","meine","ich"], correct:0, exp:"„die Vokabeln“ = Akkusativ → „mir“ (Dativ)." },
        { type:"gap", qt:"Akkusativ oder Dativ?", prompt:"Sie freut ____ über das Geschenk.",
          options:["sich","ihr","ihn","sie"], correct:0, exp:"kein Akkusativobjekt → „sich“ (Akkusativ-Form, 3. Person)." },
        { type:"mc", qt:"Regel verstehen", prompt:"Wann steht das Reflexivpronomen im Dativ?",
          options:["wenn schon ein Akkusativobjekt im Satz ist","immer in der ich-Form","nie","wenn das Verb „sich“ hat"], correct:0,
          exp:"Genau: Gibt es schon ein Akkusativobjekt, wird das Reflexivpronomen zum Dativ." },
        { type:"mc", qt:"Fehler finden", prompt:"Welcher Satz ist FALSCH?",
          options:["Ich wasche mich die Haare.","Ich wasche mich.","Ich wasche mir die Haare.","Ich kämme mich."], correct:0,
          exp:"„die Haare“ ist Akkusativ → es muss „mir“ heißen: „Ich wasche mir die Haare.“." },
        { type:"pair", qt:"Person → Akkusativ", prompt:"Ordne die Akkusativ-Reflexivpronomen zu.",
          items:[ {l:"ich", r:"mich"}, {l:"du", r:"dich"}, {l:"er/sie/es", r:"sich"}, {l:"wir", r:"uns"} ] },
        { type:"pair", qt:"Person → Dativ", prompt:"Ordne die Dativ-Reflexivpronomen zu.",
          items:[ {l:"ich", r:"mir"}, {l:"du", r:"dir"}, {l:"er/sie/es", r:"sich"}, {l:"ihr", r:"euch"} ] },
        { type:"scramble", qt:"Satz bauen (Akkusativ)", prompt:"Bau den Satz.",
          words:["Ich","interessiere","mich","sehr","für","Politik","."], answer:"Ich interessiere mich sehr für Politik ." },
        { type:"scramble", qt:"Satz bauen (Dativ)", prompt:"Bau den Satz.",
          words:["Ich","putze","mir","jeden","Morgen","die","Zähne","."], answer:"Ich putze mir jeden Morgen die Zähne ." },
        { type:"scramble", qt:"Satz bauen", prompt:"Bau den Satz.",
          words:["Wir","treffen","uns","heute","Abend","."], answer:"Wir treffen uns heute Abend ." },
        { type:"gap", qt:"Akkusativ oder Dativ?", prompt:"Kannst du ____ das gut vorstellen?",
          options:["dir","dich","du","dein"], correct:0, exp:"„das“ = Akkusativobjekt → „dir“ (Dativ): „sich etwas vorstellen“." },
        { type:"gap", qt:"Akkusativ oder Dativ?", prompt:"Bitte beeil ____!",
          options:["dich","dir","du","dein"], correct:0, exp:"kein Akkusativobjekt → „dich“ (Akkusativ): „sich beeilen“." },
        { type:"mc", qt:"Beine-Logik", prompt:"„Ich kaufe mir ein Auto.“ — Warum „mir“ und nicht „mich“?",
          options:["weil „ein Auto“ schon das Akkusativ-Bein ist","weil kaufen immer Dativ ist","weil „mir“ schöner klingt","weil „ich“ Dativ ist"], correct:0,
          exp:"„ein Auto“ besetzt das Akkusativ-Bein → das Reflexivpronomen nimmt das Dativ-Bein: „mir“." },
      ],
    },
  ],
};

if (typeof module !== "undefined") { module.exports = LESSON; }
